authors:
  thunderhawkgaming:
    name: Thunderhawk Gaming
    description: Owner
    avatar: https://github.com/Thunderhawk-Gaming.png
nightfuryvg:
    name: Night Fury
    description: Co-Owner
    avatar: https://github.com/NightFuryVG.png
starfall:
    name: Starfall
    description: Network Security Manager
    avatar: https://static.wixstatic.com/media/1bf8c6_e27a5dc5c75e45408901b6210b138baa%7Emv2.gif
jpty:
    name: JP Plays
    description: Administrator
    avatar: https://github.com/JPPlaysYT1.png
jasper1987:
    name: Jasper Le Ghost
    description: Head Moderator
    avatar: https://static.wixstatic.com/media/12679b_c717fbd69f0245299b760567f2b99f8f~mv2.png/v1/fill/w_458,h_411,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Image-empty-state.png
clonn:
    name: Clonn
    description: Administrator
    avatar: https://github.com/GloomyGalaxy.png
bd5:
    name: BusDriver5
    description: Administrator
    avatar: https://github.com/BusDriver5YT.png
coot:
    name: Canadianperson
    description: Head Administrator
    avatar: https://static.wixstatic.com/media/1bf8c6_46a05995e0a14ea687c9340c3976c9e5%7Emv2.jpg/v1/fill/w_154,h_154,al_c,lg_1,q_80,enc_auto/1bf8c6_46a05995e0a14ea687c9340c3976c9e5%257Emv2.jpg